version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    environment:
      - PROTOCOL=https
      - DOMAIN=kansalaisrajoite.fi
      - DB_URL=postgresql+psycopg2://postgres:postgres@db:5432/postgres
      - SITE_SECRET
      - DEVELOPMENT=false
      - SMTP_HOST=localhost
    expose:
      - "8000"
    depends_on:
      - db
    restart: unless-stopped
  nginx:
    image: nginx:1.17
    restart: unless-stopped
    volumes:
      - ./assets/nginx:/etc/nginx/conf.d:ro
      - ./static:/static:ro
    ports:
      - "8000:8000"
    depends_on:
      - backend
  db:
    image: postgres:12
    restart: unless-stopped
