version: '2'
services:
  backend:
    environment:
      - PROTOCOL=http
      - DOMAIN=localhost:8000
      - SITE_SECRET=supersecret
      - DEVELOPMENT=true
      - SMTP_HOST=smtp-sink
    depends_on:
      - smtp-sink
  db:
    volumes:
      # include db initialization scripts to automatically populate db
      - ./assets/initdb:/docker-entrypoint-initdb.d:ro
  smtp-sink:
      # fake smtp sink
      image: tecnativa/smtp-sink
