BEGIN TRANSACTION;

DROP TABLE IF EXISTS news;
DROP TABLE IF EXISTS vote;
DROP TABLE IF EXISTS restriction;
DROP TABLE IF EXISTS "user";

CREATE TABLE "user" (
	id SERIAL PRIMARY KEY,
	email VARCHAR(128) NOT NULL UNIQUE,
	name VARCHAR(128),
	verified BOOLEAN NOT NULL DEFAULT(FALSE),
	password CHAR(60) NOT NULL,
	city VARCHAR(32),
	admin BOOL NOT NULL DEFAULT(FALSE),
	registered TIMESTAMP NOT NULL DEFAULT(NOW())
);

CREATE TABLE restriction (
	id SERIAL PRIMARY KEY,
	created TIMESTAMP NOT NULL DEFAULT(NOW()),
	modified TIMESTAMP NOT NULL DEFAULT(NOW()),
	title TEXT NOT NULL,
	body TEXT NOT NULL,
	state TEXT CHECK (state IN ('NEW', 'APPROVED', 'REJECTED')),
	approver_id INTEGER REFERENCES "user"(id) ON DELETE SET NULL ON UPDATE CASCADE,
	user_id INTEGER REFERENCES "user"(id) ON DELETE SET NULL ON UPDATE CASCADE,
	user_name VARCHAR(128) NOT NULL,
	user_city VARCHAR(32) NOT NULL
);

CREATE TABLE vote (
	restriction_id INTEGER REFERENCES restriction(id) ON DELETE CASCADE ON UPDATE CASCADE,
	user_id INTEGER REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY (restriction_id, user_id)
);

CREATE TABLE news (
	id SERIAL PRIMARY KEY,
	created TIMESTAMP NOT NULL DEFAULT(NOW()),
	modified TIMESTAMP NOT NULL DEFAULT(NOW()),
	title TEXT NOT NULL,
	body TEXT NOT NULL,
	user_id INTEGER REFERENCES "user"(id) ON DELETE SET NULL ON UPDATE CASCADE
);

COMMIT;
